### ISSUE TITLE
default.xml set page layout to 1 column for each page

### ISSUE THREAD

**Issue by ldrooij** [NVision-Commerce-Solutions/module-customer-price-hyva-compatibility#7]
On line 2 of `view/frontend/layout/default.xml` page layout is set which results in each page defined before this module to have a 1 column layout.

```
<page layout="1column" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
```
`layout="1column'` should be removed.

**Comment by ldrooij** [comment]
I see there's already a PR for this https://github.com/NVision-Commerce-Solutions/module-customer-price-hyva-compatibility/pulls

**Comment by soloma88** [comment]
Fixed
