### ISSUE TITLE
Prices are not loaded when products items are added to the document asynchronous

### ISSUE THREAD

**Issue by ldrooij** [NVision-Commerce-Solutions/module-customer-price-hyva-compatibility#8]
When using tools to load product data asynchronous (e.g. ajax filter or infinite scroll) default prices will be shown because there is no trigger to load customer specific prices.

**Comment by soloma88** [comment]
@ldrooij Hi! Could you please clarify which extensions are you using so we can help you to customize the module and will try to investigate if we can add solution for that.

**Comment by ldrooij** [comment]
@soloma88 Currently we are using https://github.com/shellpea/advanced-elasticsuite-catalog in combination with Smile Elasticsuite. You could use that for testing purpose, but as I see it this would be an issue for any custom code loading product data asynchronous.

**Comment by ldrooij** [comment]
This is not only related to the Hyvä compatibility, but is also an issue in https://github.com/NVision-Commerce-Solutions/module-customer-price

**Comment by soloma88** [comment]
Fixed
